### ISSUE TITLE
NuGet restore failure

### ISSUE THREAD

**Issue by blakepell** [Eliasyoussef47/Configs#11]
I went to add a reference to this project in VS and I get a NuGet restore failure for it.  The version on NuGet is looking for `LocalAppDataFolder >= 1.0.3` but NuGet only has version `1.0.2` for that library (also yours).

Just wanted to share!

**Comment by Eliasyoussef47** [comment]
I'll look into it. How are you adding this package to your project exactly? I'm new to NuGet so I use the NuGet Package Manager in VS to add a package to my projects.

**Comment by blakepell** [comment]
I was using Visual Studio Community 2019 (v16.10.2).  I used the built in NuGet tool `Tools->NuGet Package Manager->Manage NuGet Packages for Solution".  Basically the Config package is looking for > `v1.0.3` of `LocalAppDataFolder` and it's only finding v1.0.2 published on NuGet.  Publishing v1.0.3 of LocalAppDataFolder or changing the version the Config library uses would fix it.

![image](https://user-images.githubusercontent.com/5958430/125367492-3c129a00-e346-11eb-91a6-27c35f18f359.png)

![image](https://user-images.githubusercontent.com/5958430/125367624-7714cd80-e346-11eb-919f-654ec428c5b1.png)

I looked through the library though, I love the simplicity of it (and it was pretty much exactly how I was going to code it).  Good stuff. :)  Thank you for sharing.

**Comment by Eliasyoussef47** [comment]
Thank you for the description. It's very late where I live and I read your issue incorrectly.
I just uploaded the 1.0.3 version of the package, give it a minute to get listed.

Thanks for the compliments. Please let me know if you have any suggestions and feel free to contribute to the project if you want to.

**Comment by blakepell** [comment]
Your update worked, will close this issue. :)  Thank you again!
